name: fwi_dev_conda_environment
channels:
  - anaconda
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - gmp=6.1.2=hb3b607b_0
  - importlib_metadata=1.1.0=py37_0
  - intel-openmp=2019.5=281
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.10.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.5=281
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=7.2.0=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - notebook=6.0.2=py37_0
  - openssl=1.1.1=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.5.2=py_0
  - pyrsistent=0.15.6=py37h7b6447c_0
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.0=py37he6710b0_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py37_0
  - setuptools=42.0.2=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - adal==1.2.2
    - ansiwrap==0.8.4
    - applicationinsights==0.11.9
    - azure-common==1.1.23
    - azure-core==1.1.1
    - azure-datalake-store==0.0.48
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==0.60.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-keyvault==2.0.0
    - azure-mgmt-resource==7.0.0
    - azure-mgmt-storage==7.0.0
    - azure-storage-blob==12.1.0
    - azureml-automl-core==1.0.76
    - azureml-automl-runtime==1.0.76.1
    - azureml-contrib-notebook==1.0.76
    - azureml-core==1.0.76
    - azureml-dataprep==1.1.33
    - azureml-dataprep-native==13.1.0
    - azureml-defaults==1.0.76
    - azureml-explain-model==1.0.76
    - azureml-interpret==1.0.76
    - azureml-model-management-sdk==1.0.1b6.post1
    - azureml-pipeline==1.0.76
    - azureml-pipeline-core==1.0.76
    - azureml-pipeline-steps==1.0.76
    - azureml-sdk==1.0.76
    - azureml-telemetry==1.0.76
    - azureml-train==1.0.76
    - azureml-train-automl==1.0.76
    - azureml-train-automl-client==1.0.76
    - azureml-train-automl-runtime==1.0.76.1
    - azureml-train-core==1.0.76
    - azureml-train-restclients-hyperdrive==1.0.76
    - azureml-widgets==1.0.76
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - boto==2.49.0
    - boto3==1.10.37
    - botocore==1.13.37
    - cffi==1.13.2
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.2
    - configparser==3.7.4
    - contextlib2==0.6.0.post1
    - cryptography==2.8
    - cycler==0.10.0
    - cython==0.29.14
    - dill==0.3.1.1
    - distro==1.4.0
    - docker==4.1.0
    - docutils==0.15.2
    - dotnetcore2==2.1.11
    - fire==0.2.1
    - flake8==3.7.9
    - flask==1.0.3
    - fusepy==3.0.1
    - future==0.18.2
    - gensim==3.8.1
    - gunicorn==19.9.0
    - idna==2.8
    - imageio==2.6.1
    - interpret-community==0.2.3
    - interpret-core==0.1.19
    - ipywidgets==7.5.1
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jeepney==0.4.1
    - jmespath==0.9.4
    - json-logging-py==0.2
    - jsonform==0.0.2
    - jsonpickle==1.2
    - jsonsir==0.0.2
    - keras2onnx==1.6.0
    - kiwisolver==1.1.0
    - liac-arff==2.4.0
    - lightgbm==2.3.0
    - matplotlib==3.1.2
    - mccabe==0.6.1
    - msrest==0.6.10
    - msrestazure==0.6.2
    - ndg-httpsclient==0.5.1
    - networkx==2.4
    - nimbusml==1.6.1
    - numpy==1.16.2
    - oauthlib==3.1.0
    - onnx==1.6.0
    - onnxconverter-common==1.6.0
    - onnxmltools==1.4.1
    - packaging==19.2
    - pandas==0.23.4
    - papermill==1.2.1
    - pathspec==0.6.0
    - patsy==0.5.1
    - pillow==6.2.1
    - pmdarima==1.1.1
    - protobuf==3.11.1
    - psutil==5.6.7
    - pyasn1==0.4.8
    - pycodestyle==2.5.0
    - pycparser==2.19
    - pyflakes==2.1.1
    - pyjwt==1.7.1
    - pyopenssl==19.1.0
    - pyparsing==2.4.5
    - python-dotenv==0.10.3
    - python-easyconfig==0.1.7
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyyaml==5.2
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - resource==0.2.1
    - ruamel-yaml==0.15.89
    - s3transfer==0.2.1
    - scikit-image==0.16.2
    - scikit-learn==0.20.3
    - scipy==1.1.0
    - secretstorage==3.1.1
    - shap==0.29.3
    - skl2onnx==1.4.9
    - sklearn-pandas==1.7.0
    - smart-open==1.9.0
    - statsmodels==0.10.2
    - tenacity==6.0.0
    - termcolor==1.1.0
    - textwrap3==0.9.2
    - tqdm==4.40.2
    - typing-extensions==3.7.4.1
    - urllib3==1.25.7
    - websocket-client==0.56.0
    - werkzeug==0.16.0
    - wheel==0.30.0
    - widgetsnbextension==3.5.1
prefix: /data/anaconda/envs/fwi_dev_conda_environment
