name: seismic-interpretation
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - pip
  - pytorch
  - jupyter
  - ipykernel
  - torchvision
  - pandas
  - opencv
  - scikit-learn
  - pip:
    - segyio
    - pytorch-ignite
    - fire
    - toolz
    - tabulate==0.8.2
    - Jinja2
    - gitpython
    - tensorflow # Installing for Tensorboard
    - tensorboard
    - tensorboardx
    - tqdm
    - invoke
    - yacs
    - albumentations
    - black
    - pylint
    - scipy==1.1.0

